---
title: 'Post Election Campaign Narrative'
author: Jacqui Schlesinger
date: '2024-12-09'
slug: post-election-campaign-narrative
categories: []
tags: []
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
set.seed(02138)
```

For my final blog post, I will analyze how and why states– in particular New Hampshire– deviate from forecasts using expert predictions of the states’ outcome and an analysis of news sources and down-ballot races. This blog post will begin with an overview of New Hampshire and its electoral history, then analyze how similar the expertly predicted outcomes for the state deviated from the actual outcome, and finally use scholarly literature and news sources to understand how campaign and candidate effects could have contributed to this deviation. In 2024, Vice President Kamala Harris won New Hampshire with 50.9% of the vote (418,496 votes) to incoming President Donald Trump’s 48.1% (395,578 votes). An additional 8,079 votes went to third party candidates. 

### About New Hampshire
	New Hampshire, known as the Live Free or Die state, was one of the original 13 colonies of the United States. It has a small international border with Canada in the north and borders Massachusetts, Maine, Vermont, and the Atlantic Ocean on other sides. New Hampshire is known for its nature, including the [highest peak in the northeast](https://www.visitwhitemountains.com/things-to-do/outdoors/mount-washington/) and [more than 1300 lakes and 40 rivers](https://www.nh.gov/almanac/fast-facts.htm), and many threatened animal species. Other large geographic features include the White Mountains in the north and Lake Winnipesaukee, the state’s [largest lake](https://www.lakesregion.org/our-lakes/lake-winnipesaukee/). According to the [New Hampshire Department of Business and Economic Affairs](https://www.nheconomy.com/key-industries), its main industries are advanced manufacturing, technology, life sciences, and tourism and hospitality. By real value added to the GDP of the state in 2023, the [largest industry](https://www.statista.com/statistics/1065116/new-hampshire-real-gdp-by-industry/) was finance, insurance, real estate, rental, and leasing, followed by professional and business services. 

The state has a population of 1,377,529 [as of the 2020 Census](https://data.census.gov/profile/New_Hampshire?g=040XX00US33). New Hampshire has two members of the US Senate and two members of the US House. The [2023 American Community Survey](https://data.census.gov/profile/New_Hampshire?g=040XX00US33) estimated that 40.7% of residents have a bachelor's degree or higher and the employment rate is 64.7% (higher than US average by 4 points). Compared the US median age measured by this survey of 39.2, New Hampshire is older on average, with a median age of 43.4. The three largest age groups in the state are 50 to 54, 55 to 59 and 60 to 64. Given how we have seen in past weeks that this age group's general lean is slightly towards Trump, it would be interesting to look at the demographic voting data if it is available. New Hampshire's older population (65 years or older) is also [larger than the US average](https://data.census.gov/profile/New_Hampshire?g=040XX00US33). More demographics will be explored as we break down the results by county and compare them to predictions below. 


### New Hampshire as a Swing State
In the 2024 presidential election, New Hampshire was not considered one of the seven toss up states in the few months leading up to the election, instead considered to be leaning to the democrats. Since 2000, [New Hampshire has voted](https://ballotpedia.org/Presidential_voting_trends_in_New_Hampshire) Democratic 85.7% and Republican 14.3% of the time. The New Hampshire winners since 2000 are below:

- 2000: George W Bush
- 2004: John Kerry
- 2008: Barack Obama 
- 2012: Barack Obama 
- 2016: Hillary Clinton
- 2020: Joe Biden 
- 2024: Kamala Harris

The state last voted for a Republican in 2000, and since has voted for the Democrat in each election, being incorrect in 2004, 2016, and 2024 in consistency with the overall winner of the electoral college. 

In 2020, [local news described](https://www.wmur.com/article/new-hampshire-president-election-results-history/34464312) the state as a battleground state that could help determine the outcome of the election. [Reporting by Slate](https://slate.com/news-and-politics/2020/11/new-hampshire-still-swing-state.html) in 2020 found that while 2016 was the second smallest margin of all states, New Hampshire may be moving away from the swing state moniker it has had since the 1990s. Given it has gone blue every election since 2000, this may be the case, but these results have all been by incredibly slim margins, meaning it does not seem New Hampshire is quite set on being blue for the foreseeable future. This can also be seen by down ballot results and campaign involvement in the states. New Hampshire remains an up for grabs, tight margin state. 


### The 2024 New Hampshire Ballot
Down ballot candidates in 2024

### Presidential Election Predictions in New Hampshire
I did not calculate this
What did Sabato, 538, real clear, and cook say

### Analysis of Expert Prediction Closeness
Use same calculations as analysis

### Review of the 2024 Presidential Campaign in NH
News sources

### Campaign and Candidate Effects As Deviations from Predictions
Drawing on the literature from the class and, if necessary, other scholarly sources, speculate on how the campaign and candidates may have contributed to the deviations from the forecasted outcome
